### ISSUE TITLE
퀘스트 관련

### ISSUE THREAD

**Issue by norhu1130** [K9714/net_rmxp_project#6]
카페를보면 1.7버전에서 퀘스트를 추가한다고했습니다.
퀘스트의경우 서버전처리인지 클라이언트 전처리인지 궁금합니다

**Comment by K9714** [comment]
서버 전처리 방식입니다. 퀘스트 제작을 위해 각 상황에 맞는 event 함수들을 세팅하고 있었고(ex 몬스터 잡을시 진행도 증가 등) DB Manager 쪽에서 모두 처리가 가능하도록 시도하려 했습니다.

퀘스트 부분에 대한 것들은 작업하던 것들이 있으므로 7월 중으로 업데이트 하겠습니다.

**Comment by norhu1130** [comment]
확인하였습니다.
